### ISSUE TITLE
Interrupt issue

### ISSUE THREAD

**Issue by zhaozhenhong5** [sandervandevelde/TtnAzureBridge#2]
I found an issue that the bridge will be stoped when it run for some times. I must close an run it again. Do you know why？

**Comment by sandervandevelde** [comment]
Hello zhaozhenhong5, 

No, I'm not sure why. I have seen it with bad (wifi) connections.

But the fact this exception is not handled is by design. Please run this application as webjob. When it fails, the webjob will automatically restart the job.

**Comment by sandervandevelde** [comment]
After a few hours of debugging, I was able to fix the Transient error which caused an quite uncatchable exception. 
Please use the latest version and check if this fixes your issue.
